In [1]:
import pandas as pd

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("traces.db")
df = pd.read_sql_query("SELECT * FROM spans", conn)
conn.close()

df.head()

,name,start_time,end_time,input_tokens,output_tokens,cost
0,search,1784223990712297400,1784223990720175700,NaN,NaN,None
1,llm,1784223990725174700,1784223996553882000,7111.0,124.0,None
2,rag,1784223990712297400,1784223996562078500,NaN,NaN,None
3,search,1784224298890724500,1784224298896858400,NaN,NaN,None
4,llm,1784224298907952000,1784224301927603700,7111.0,109.0,None

In [5]:
df_llm = df[df['name'] == 'llm']
df_llm

,name,start_time,end_time,input_tokens,output_tokens,cost
1,llm,1784223990725174700,1784223996553882000,7111.0,124.0,None
4,llm,1784224298907952000,1784224301927603700,7111.0,109.0,None
7,llm,1784224315587231900,1784224318286365200,7111.0,92.0,None
10,llm,1784224336674676800,1784224340617887500,7111.0,97.0,None